# Generated by Django 4.2.7 on 2024-08-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
