# Generated by Django 4.2.7 on 2024-08-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_school_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='slug',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
