# Generated by Django 4.2.7 on 2024-08-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_campus_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='price',
            field=models.PositiveBigIntegerField(default=100),
        ),
    ]
