# Generated by Django 4.2.7 on 2024-08-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0006_rename_user_name_siteuser_username_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
